name: yt_sync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  audio_session: ^0.2.2
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  json_annotation: ^4.9.0
  just_audio: ^0.10.5
  riverpod_annotation: ^4.0.0
  youtube_explode_dart: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.10.5
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  go_router_builder: ^4.1.3

flutter:
  uses-material-design: true
